Repository DeveloperAcademy-POSTECH/2025-C4-M4-Connectivity, pull requests merged in 2025-07, with the labels that each got.

#163 ✨ Feat: #80 앱 아키텍처 스캐폴드 및 네비게이션 흐름 구성
  Package.resolved
  Package.swift
  README.md
  Saboteur.xcodeproj/project.pbxproj
  Saboteur.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Saboteur.xcodeproj/project.xcworkspace/xcuserdata/seolin.xcuserdatad/UserInterfaceState.xcuserstate
  Saboteur/App/AppDelegate.swift
  Saboteur/App/RootCoordinator.swift
  Saboteur/App/SaboteurApp.swift
  Saboteur/ContentView.swift
  Saboteur/Core/Models/Item.swift
  Saboteur/Core/Network/NetworkMonitor.swift
  Saboteur/Core/Network/P2PKitManager.swift
  Saboteur/Core/Persistence/SwiftDataContainer.swift
  Saboteur/Core/Utilities/Logger.swift
  Saboteur/Features/GamePlay/GameCoordinator.swift
  Saboteur/Features/GamePlay/GameView.swift
  Saboteur/Features/GamePlay/GameViewModel.swift
  Saboteur/Features/Lobby/LobbyCoordinator.swift
  Saboteur/Features/Lobby/LobbyView.swift
  Saboteur/Features/Lobby/LobbyViewModel.swift
  Saboteur/Features/Profile/ProfileCoordinator.swift
  Saboteur/Features/Profile/ProfileView.swift
  Saboteur/Features/Profile/ProfileViewModel.swift
  Saboteur/SaboteurApp.swift
Labels: 📝 docs, ♻️ refactor

#173 ♻️ Refactor : P2PKit 로컬 패키지화 및 `P2PTicTacToe` 완전 제거
  P2PKit/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  P2PKit/Package.swift
  P2PKit/Sources/P2PKit/P2PNetwork.swift
  P2PKit/Sources/P2PKit/Private/P2PHostSelector.swift
  P2PKit/Sources/P2PKit/Private/P2PLogger.swift
  P2PKit/Sources/P2PKit/Private/P2PSession.swift
  P2PKit/Sources/P2PKit/Private/WeakArray.swift
  P2PKit/Sources/P2PKit/Public/P2PEventService.swift
  P2PKit/Sources/P2PKit/Public/P2PSynced.swift
  P2PKit/Sources/P2PKit/Public/P2PUtils.swift
  P2PKit/Sources/P2PKit/Public/Peer.swift
  P2PKit/Tests/P2PKitTests/P2PKitTests.swift
  P2PTicTacToe/Assets.xcassets/AccentColor.colorset/Contents.json
  P2PTicTacToe/Assets.xcassets/AppIcon.appiconset/Contents.json
  P2PTicTacToe/Assets.xcassets/Contents.json
  P2PTicTacToe/ChangeNameView.swift
  P2PTicTacToe/Game/0-1-1-LobbyView.swift
  P2PTicTacToe/Game/0-1-DuoGameView.swift
  P2PTicTacToe/Game/0-2-1-TripleLobbyView.swift
  P2PTicTacToe/Game/0-2-TripleGameView.swift
  P2PTicTacToe/Game/0-3-SquadGameView.swift
  P2PTicTacToe/Game/0-GameStartTab.swift
  P2PTicTacToe/Game/1-GameView.swift
  P2PTicTacToe/Info.plist
  P2PTicTacToe/Navigation/AppRouter.swift
  P2PTicTacToe/P2PTicTacToeApp.swift
  P2PTicTacToe/Preview Content/Preview Assets.xcassets/Contents.json
  P2PTicTacToe/View+Extensions.swift
  Package.swift
  Saboteur.xcodeproj/project.pbxproj
  Saboteur.xcodeproj/project.xcworkspace/xcuserdata/seolin.xcuserdatad/UserInterfaceState.xcuserstate
  Saboteur.xcodeproj/xcuserdata/seolin.xcuserdatad/xcschemes/xcschememanagement.plist
  Saboteur/Features/Connect/ConnectView.swift
Labels: 🐛 bug, ♻️ refactor

#175 ✨ Feature. #74, #147, #148 모달 뷰 추가 및 P2P 연결 디테일 수정
  P2PKit/Sources/P2PKit/Private/P2PSession.swift
  P2PKit/Sources/P2PKit/Public/P2PSynced.swift
  Saboteur.xcodeproj/project.pbxproj
  Saboteur/Core/Models/Item.swift
  Saboteur/Features/Connect/ConnectLobbyView.swift
  Saboteur/Features/Connect/ConnectView.swift
  Saboteur/Features/GamePlay/GameResultView.swift
  Saboteur/Features/GamePlay/GameView.swift
  Saboteur/Features/Lobby/ChangeNameView.swift
  Saboteur/Features/Lobby/ChoosePlayerView.swift
  Saboteur/Features/Lobby/LobbyView.swift
Labels: 📡 comm

#176 ✨ Feature: CLI 기반의 사보타지 게임 로직을 iOS 포팅
  Saboteur.xcodeproj/project.pbxproj
  Saboteur.xcodeproj/project.xcworkspace/xcuserdata/seolin.xcuserdatad/UserInterfaceState.xcuserstate
  Saboteur.xcodeproj/xcuserdata/seolin.xcuserdatad/xcschemes/xcschememanagement.plist
  Saboteur/Config/Constants.swift
  Saboteur/Core/Models/Board.swift
  Saboteur/Core/Models/BoardCell.swift
  Saboteur/Core/Models/Card.swift
  Saboteur/Core/Models/Player.swift
  Saboteur/Features/GamePlay/GameView.swift
  Saboteur/Info.plist
Labels: 🎮 engine

#178 ✨ Feat. #142 승리 로직 구현 - placable 조건 오류 개선 포함
  GameEngine/main.swift
Labels: 🎮 engine

#186 # ✨ Feat: 게임 코어 모델 패키지화 및 접근제어자 public으로 전환
  GameEngine/main.swift
  Saboteur.xcodeproj/project.pbxproj
  Saboteur.xcodeproj/project.xcworkspace/xcuserdata/seolin.xcuserdatad/UserInterfaceState.xcuserstate
  Saboteur.xcodeproj/xcuserdata/seolin.xcuserdatad/xcschemes/xcschememanagement.plist
  Saboteur/Config/Constants.swift
  SaboteurKit/.gitignore
  SaboteurKit/Package.swift
  SaboteurKit/Sources/SaboteurKit/Models/Board.swift
  SaboteurKit/Sources/SaboteurKit/Models/BoardCell.swift
  SaboteurKit/Sources/SaboteurKit/Models/Card.swift
  SaboteurKit/Sources/SaboteurKit/Models/Player.swift
  SaboteurKit/Sources/SaboteurKit/SaboteurKit.swift
Labels: 🎮 engine, ♻️ refactor

#196 🐛 Fix. P2Pkit 타입오류 수정
  P2PKit/Sources/P2PKit/Private/WeakArray.swift
  Saboteur.xcodeproj/project.pbxproj
  Saboteur/Assets.xcassets/AppIcon.appiconset/Contents.json
  Saboteur/Assets.xcassets/AppIcon.appiconset/kirby.jpg
Labels: 🐛 bug, 📡 comm

#211 ✨ Feat. 공용 카드덱 생성 및 cardSet 구조체 위치 변경
  GameEngine/main.swift
  Saboteur.xcodeproj/project.pbxproj
  SaboteurKit/Sources/SaboteurKit/Models/Card.swift
  SaboteurKit/Sources/SaboteurKit/Models/CardDeck.swift
Labels: 🎮 engine

#220 ✨ Feature: #219 Color-chip-setting-at-assets
  Saboteur/Assets.xcassets/Color/ Grayscale/Black.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/ Grayscale/Contents.json
  Saboteur/Assets.xcassets/Color/ Grayscale/Gray2.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/ Grayscale/White-bg.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/ Grayscale/White.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/ Grayscale/gray.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Contents.json
  Saboteur/Assets.xcassets/Color/Emerald/Contents.json
  Saboteur/Assets.xcassets/Color/Emerald/Emerald1.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Emerald/Emerald2.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Emerald/Emerald3.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Emerald/EmeraldYellow.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Ivory/Contents.json
  Saboteur/Assets.xcassets/Color/Ivory/Ivory1.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Ivory/Ivory2.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Ivory/Ivory3.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Ivory/Ivory4.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Secondary/Blue1.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Secondary/Blue2.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Secondary/Blue3.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Secondary/Blue4.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Secondary/Contents.json
  Saboteur/Assets.xcassets/Color/Secondary/Yellow1.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/Secondary/Yellow2.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/etc/Contents.json
  Saboteur/Assets.xcassets/Color/etc/Green.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/etc/Mint.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/etc/Orange.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/etc/Pink.colorset/Contents.json
  Saboteur/Assets.xcassets/Color/etc/Red.colorset/Contents.json
Labels: 🎨 UI/UX

#218 ♻️ Refactor : 카드셋을 17종으로 확장 및 enum 기반 구조 적용
  SaboteurKit/Sources/SaboteurKit/Models/Card.swift
Labels: 🐛 bug, 🎮 engine, ♻️ refactor

#263 ♻️ Refactor. 누락된 SwiftFormat 일괄 적용 및 중복 asset 경로 이동
  GameEngine/main.swift
  Saboteur/App/AppDelegate.swift
  Saboteur/App/BackgroundTaskManager.swift
  Saboteur/Assets.xcassets/Color/Emerald/emerald2.colorset/Contents.json
  Saboteur/Assets.xcassets/Contents.json
  Saboteur/Extensions/Font+extension.swift
  Saboteur/Features/Lobby/ChangeNameView.swift
  Saboteur/Resources/Assets.xcassets/Color/ Grayscale/gray2_deep.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/ Grayscale/white_bg.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/Emerald/emerald_yellow.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/Secondary/blue3_deep.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/etc/Orangedeep.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/etc/Reddeep.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/etc/mint_deep.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/etc/orange_deep.colorset/Contents.json
  Saboteur/Resources/Assets.xcassets/Color/etc/red_deep.colorset/Contents.json
  SaboteurKit/Sources/SaboteurKit/Models/Card.swift
  SaboteurKit/Sources/SaboteurKit/Models/CardDeck.swift
  SaboteurKit/Sources/SaboteurKit/Models/Player.swift
Labels: ♻️ refactor

#268 ✨ Feat: #223 앱 최초 접속 시 닉네임 설정 모달 열림
  P2PKit/Sources/P2PKit/Public/Peer.swift
  Saboteur.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Saboteur/Extensions/DropShadow+extension.swift
  Saboteur/Features/Component/FooterButton.swift
  Saboteur/Features/GamePlay/GameResultView.swift
  Saboteur/Features/Lobby/ChangeNameView.swift
  Saboteur/Features/Lobby/LobbyView.swift
  Saboteur/Resources/Assets.xcassets/Button/x_button.imageset/x_button.svg
Labels: 🎨 UI/UX

#271 🐛 Fix: 세션연결 후 광고-브라우져검색정지 (3, 4인 플레이 중 한명이 나간 후 제 3자가 안들어오게 하기 위함)
  P2PKit/Sources/P2PKit/P2PNetwork.swift
  P2PKit/Sources/P2PKit/Private/P2PSession.swift
  Saboteur/Features/Connect/ConnectView.swift
Labels: 🐛 bug, 📡 comm

#278 ✨ Feat: #271 카드덱 자동 분배 및 세션 오류 롤백
  P2PKit/Sources/P2PKit/P2PNetwork.swift
  P2PKit/Sources/P2PKit/Private/P2PSession.swift
  Saboteur/Features/Connect/ConnectView.swift
  Saboteur/Features/GamePlay/GameBoardView.swift
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
  Saboteur/Features/GamePlay/Models/PeerPlayer.swift
Labels: 🐛 bug, 🎮 engine, ♻️ refactor, 📡 comm

#287 ✨ Feature: 타임아웃 시 자동으로 카드 제거 후 새 카드 지급 처리
  Saboteur/Features/GamePlay/GameBoardView.swift
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
Labels: 🎮 engine

#289 ✨ Feat: #288 goalIndex 동기화 및 호스트 여부 확인 기능 추가
  P2PKit/Sources/P2PKit/P2PNetwork.swift
  Saboteur/Features/GamePlay/Component/BoardGridView.swift
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
  SaboteurKit/Sources/SaboteurKit/Models/Board.swift
Labels: 🎮 engine, 📡 comm, 🎨 UI/UX

#295 ✨Feature. #237 목적지 확인 map 카드 확장
  GameEngine/main.swift
  SaboteurKit/Sources/SaboteurKit/Models/Board.swift
Labels: 🎮 engine

#294 ✨ Feature: #293 골 영역 도달 시 골 카드 공개 기능 추가
  Saboteur/Features/GamePlay/Component/GridCellView.swift
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
  SaboteurKit/Sources/SaboteurKit/Models/Board.swift
  SaboteurKit/Sources/SaboteurKit/Models/Card.swift
  SaboteurKit/Sources/SaboteurKit/Models/CardDeck.swift
Labels: 🐛 bug, 🎮 engine, 📡 comm, 🎨 UI/UX

#297 ✨ Feature: #296 맵 카드 사용 시 Toast 타겟 구분 및 카드 시각적 피드백 기능 추가
  Saboteur/Features/Enums/ToastTarget.swift
  Saboteur/Features/GamePlay/Component/BoardGridView.swift
  Saboteur/Features/GamePlay/Component/GridCellView.swift
  Saboteur/Features/GamePlay/GameBoardView.swift
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
  Saboteur/Features/GamePlay/Models/Coordinate.swift
  Saboteur/Features/GamePlay/Models/TargetedToast.swift
Labels: 📡 comm, 🎨 UI/UX

#299 ✨Feature: #236 마지막 열 카드 설치 제한
  GameEngine/main.swift
  SaboteurKit/Sources/SaboteurKit/Models/Board.swift
  SaboteurKit/Sources/SaboteurKit/Models/Card.swift
Labels: 🐛 bug, 🎮 engine, ♻️ refactor

#302 🐛Fix: goalCheck 오류 수정
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
  SaboteurKit/Sources/SaboteurKit/Models/Board.swift
Labels: 🐛 bug, 🎮 engine, 🎨 UI/UX

#309 🐛 Fix: #308 MPC P2P 세션 구조 및 초대 로직 통합
  P2PKit/Sources/P2PKit/P2PNetwork.swift
  P2PKit/Sources/P2PKit/Private/P2PHostSelector.swift
  P2PKit/Sources/P2PKit/Private/P2PSession.swift
Labels: 🐛 bug, 🎮 engine

#317 🐛Fix. bomb 카드 오류 수정
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
Labels: 🐛 bug, 🎮 engine, 🎨 UI/UX

#320 ✨Feat. 카드 덱 밸런싱 및 카드 추가
  SaboteurKit/Sources/SaboteurKit/Models/CardDeck.swift
Labels: 🎮 engine

#321 🎨 Design: #306 UI QA 반영, 토스트 수정
  Saboteur.xcodeproj/project.pbxproj
  Saboteur/Extensions/Keyboard+extension.swift
  Saboteur/Features/Component/FooterButton.swift
  Saboteur/Features/Connect/ConnectView.swift
  Saboteur/Features/GamePlay/Component/BoardGridView.swift
  Saboteur/Features/GamePlay/Component/GridCellView.swift
  Saboteur/Features/GamePlay/GameBoardViewModel.swift
  Saboteur/Features/GamePlay/GameResultView.swift
  Saboteur/Features/Lobby/ChangeNameView.swift
  Saboteur/Features/Lobby/LobbyView.swift
  Saboteur/Resources/Assets.xcassets/Card/start_2.imageset/start.png
  Saboteur/Resources/Assets.xcassets/Logo.imageset/Contents.json
  Saboteur/Resources/Assets.xcassets/Logo.imageset/Image.png
  Saboteur/Resources/Assets.xcassets/Logo.imageset/Logo.svg
  SaboteurKit/Sources/SaboteurKit/Models/Board.swift
Labels: 🎨 UI/UX
